### ISSUE TITLE
Changing DAS status to ready

### ISSUE THREAD

**Issue by schmerl** [ivoysey/brasscomms#11]
Need to know:
(a) when the robot is ready (e.g., odom received message printed)
(b) when Rainbow is ready, and start probes

**Comment by ivoysey** [comment]
this commit seems to cause das ready to not get sent before odom recieved https://github.com/ivoysey/brasscomms/commit/e703b9aa555b5824be52f090231d98ef98cb5294

**Comment by ivoysey** [comment]
bradley's commit of rainbow integration from last week closes this.
