### ISSUE TITLE
Challenge problem start up

### ISSUE THREAD

**Issue by schmerl** [ivoysey/brasscomms#12]
Determine the JSON format that LL will need to provide to start up. As per the 1/24 meeting, it should look something like this:
```
{start_loc: String, // node id from the map
 start_yaw: Float, // 0..2PI indicating the starting rotation of the robot. 0 indicates pointing in the positive x direction (EAST)
 target_loc: String, // node id from the map 
 enable_adaptation: Boolean, // Whether adaptation should be enabled in this case
 // the following will probably not be used in this phase
 initial_voltage: Integer, // See parameter spec for range
 initial_obstacle: Boolean, // Whether there is to be an obstacle at startup
 initial_obstacle_location: {x : Float, y: Float}. // The position on the map of the obstacle
 sensor_perturbation: {x : Integer, y: Integer, z : Integer, p : Integer, y : Integer, r : Integer} // The initial perturbation of the kinect sensor (0,0,0,0,0,0,0) by default
}
```
Process:
1. Decide on final format and send to LL
2. Implement in brasscomms at brasscomms startup

**Comment by schmerl** [comment]
Changed this to: (in particular, enable_adaptation has changed to handle both CP1 and CP2)

{
  start_loc: String,           // node id from the map
  start_yaw: Float,            // 0..2PI indicating the starting rotation of the robot. 0 indicates pointing in the positive x axis(EAST)
  target_loc: String,          // node id from the map 
  enable_adaptation: String,   // One of CP1_NoAdaptation, CP2_NoAdaptation, CP1_Adaptation, CP2_Adaptation

  // the following will probably not be used in this phase; we discussed these, but do we really need them
  initial_voltage: Integer,    // valid values are defined above as batteryLevel
  initial_obstacle: Boolean,   // Whether there is to be an obstacle at startup
  initial_obstacle_location:   // {x : Float, y: Float}. // The position on the map of the obstacle
  sensor_perturbation: {x : Integer, y: Integer, z : Integer, p : Integer, y : Integer, r : Integer} 
                               // The initial perturbation of the kinect sensor (0,0,0,0,0,0,0) by default
}

**Comment by ivoysey** [comment]
This is in https://github.com/ivoysey/brasscomms/issues/28 and current code as of the time of writing.
