### ISSUE TITLE
Write module to read in the map_data and convert between coordinates and waypoints (and vice versa)

### ISSUE THREAD

**Issue by schmerl** [ivoysey/brasscomms#18]
We need to work out a good place for the json file -- currently it's at the top level, but perhaps it needs to be moved to catkin_ws/src/cp_gazebo/maps?

**Comment by ivoysey** [comment]
I believe that with the module Josh wrote and the JSON files provided by Javier, this is morally complete. It may not scale, but we can worry about that in the future.
