### ISSUE TITLE
Work out how to send various statuses to LL

### ISSUE THREAD

**Issue by schmerl** [ivoysey/brasscomms#20]
In particular, we need to work out how we send:
(a) MISSION_HALTED
(b) MISSION_ABORTED

(These will be different in the base and adaptation case.) I think LL is going to use this to determine when the test has finished, in addition to the upper bound.

**Comment by ivoysey** [comment]
there's some difference between how to start up in the base case (just odom) and in the adaptive case (rainbow). more generally need to know how to know when to send the other messages as well -- ADAPTATION STARTING, etc.

**Comment by schmerl** [comment]
Yes. Just need to check that I'm sending it at the right time.
