### ISSUE TITLE
make sure we have access to ROS logs post hoc

### ISSUE THREAD

**Issue by ivoysey** [ivoysey/brasscomms#25]
TEST_FOLDER_URI will get copied out of the VM, so that we have it for forensics. so ~/.ros should get copied there, or can we configure ros to put the logs in the test directory and then just use roslog?

**Comment by ivoysey** [comment]
maybe use their log just for DAS_ERROR? like if we can't get access to the TH, so we can write it somewhere and not have no idea what happened.

**Comment by joshsunshine** [comment]
Maybe point ROS' logging infrastructure at the test folder so we don't have to copy

**Comment by ivoysey** [comment]
looks like it's easy to have ros write logs to a different directory:

http://wiki.ros.org/rospy/Overview/Logging
http://wiki.ros.org/rospy/Overview/Logging#overriding_node_log_file

**Comment by joshsunshine** [comment]
Setting environment variables seems like more of a pain in the ass than I thought so I moved this to the code freeze milestone.

**Comment by ivoysey** [comment]
our goal should be to have all the logs for each ros node appear in the same structure they currently do in `~/.ros/logs` but in `/rest/roslogs`

**Comment by joshsunshine** [comment]
The problem is that all of the standard ways of setting up environment variables for ROS are in files that are generated by catkin. We'll figure it out, but not today.

**Comment by ivoysey** [comment]
closed by this https://github.com/schmerl/LLStaging/commit/079145c76ee9e34b98cb4acc12e5f303de08043a
