### ISSUE TITLE
remove th_das_error in action end points

### ISSUE THREAD

**Issue by ivoysey** [ivoysey/brasscomms#26]
should just be TH errors, per definition of DAS_ERROR. since it's not a start up or processing test specific information, we have no business sending those.

this is related to refactoring the tops of the action endpoint implementations.

**Comment by joshsunshine** [comment]
Second pass, with refactoring: https://github.com/ivoysey/brasscomms/tree/afe907576bc37d410bcb63246f6f6f7070dc6d45
