### ISSUE TITLE
get pylint to run O(cleanly)

### ISSUE THREAD

**Issue by ivoysey** [ivoysey/brasscomms#30]
(ish)

it cares about some stuff like spacing conventions that we can either ignore or build a style file for our own codebase and go from there. but it's a good idea more generally; we're currently in the rough according to its score, and it'll probably catch at least one stupid bug.

**Comment by ivoysey** [comment]
there are some outstanding issues that don't pass pylint. some of them i've decided to ignore by adding them to the `.pylintrc` file, like: broad exception catching because we're doing it for logging which is the right reason; some variable names that are out of spec for PEP8; etc.

problems that remain are mostly down to global variable usage, which i agree is a bad habit but feel forced into by the Flask API.

**Comment by joshsunshine** [comment]
- [ ] Clean up all the imports in gazebo_interface.py
