### ISSUE TITLE
decide what to do with th_ack and th_error

### ISSUE THREAD

**Issue by ivoysey** [ivoysey/brasscomms#31]
whenever we post to the TH we get back either TH_ACK or TH_ERROR. I have no idea what to do with those, currently we just bind a variable to the result of the post and then ignore it.

it's not clear to me that we care if we get ACKs because we just keep doing stuff; we never block on waiting to know that our message went through.

the spec says that if they send us TH_ERROR they can shut down the test arbitrarily quickly _after sending_ the TH_ERROR. so that means we don't even have a gaurantee that we get it before the test gets shut down. without that assumption, it's not recoverable. and it's probably not recoverable anyway.

so it's possible that ignoring these is the right thing to do, but we should "make a design decision and document it".

**Comment by joshsunshine** [comment]
> As far as the purpose of the TH_ACK and TH_ERROR messages, the abstract interface attempted to define all messages exchanged between the TH and the DAS, and that includes the very simple HTTP 200 and 400 responses.  If we weren’t using a REST interface, these would be defined differently in the concrete implementation, and some choices of protocol may not even require a response.  Since HTTP does send responses, we’ve covered them using these message types.  **We don’t expect you to do anything with these messages.**
