### ISSUE TITLE
Make sure API parameter checking is right

### ISSUE THREAD

**Issue by schmerl** [ivoysey/brasscomms#59]
- [ ]  Coordinates for `place_obstacle` are consistent with wiki but not consistent with map (i.e., currently not possible to place an obstacle on the path)
- [x] In `place_obstacle` (and probably elsewhere) `65` is not considered a float, and so a malformed expression is returned. Has to be `65.0` currently - let's accept `65`.
- [x] The rectangle returned on `place_obstacle` doesn't look right. E.g., if placing obstacle at `19.8, 65.0`, I get a rectangle of: topleft: `(18.6, 63.8)`,  bottom right: `(21.0, 21.0)`

**Comment by ivoysey** [comment]
This is the scratch work I did to figure out how to return the safety margin in `place_obstacle`, with the following explanation:
![img_0370](https://cloud.githubusercontent.com/assets/4099104/23370849/06a8b2c0-fce4-11e6-8a5c-d9ef4df68f03.JPG)

- The model file specifies that the obstacle is "1.8 1.8 1.5", which I took to mean that it's not quite a cube but has a 1.8m^2 footprint
- (x,y) is provided by the post to the endpoint, which I take to be the desired center for the obstacle
- This means that the buffer is `((1.8/2) + 0.3) m = 1.2 m` off from (x,y)

This is implemented by just adding and subtracting the constants I computed off line in https://github.com/ivoysey/brasscomms/blob/master/src/brasscomms.py#L326

Am I using the wrong frame of reference?

**Comment by schmerl** [comment]
Logic is write - implementation is wrong. https://github.com/ivoysey/brasscomms/blob/master/src/brasscomms.py#L330 uses the x attr not the y.

**Comment by ivoysey** [comment]
D'oh! Great catch, thanks.

**Comment by ivoysey** [comment]
from looking at
```         {"node-id": "l1", "coord" : {"x" : 14.8, "y" : 69}, "connected-to": ["l2" ] },
         {"node-id": "l2", "coord" : {"x" : 19.8, "y" : 69}, "connected-to": ["l1", "c1", "c2" ] },
         {"node-id": "l3", "coord" : {"x" : 42.5, "y" : 69}, "connected-to": ["c2", "c3", "l4" ] },
         {"node-id": "l4", "coord" : {"x" : 52.2, "y" : 69}, "connected-to": ["l3", "ls", "l5" ] },
         {"node-id": "l5", "coord" : {"x" : 52.2, "y" : 58.8}, "connected-to": ["l4", "l6" ] },
         {"node-id": "l6", "coord" : {"x" : 42.5, "y" : 58.8}, "connected-to": ["l5", "c3", "c4" ] },
         {"node-id": "l7", "coord" : {"x" : 19.8, "y" : 58.8}, "connected-to": ["c4", "c1" ] },
         {"node-id": "ls", "coord" : {"x" : 52.2, "y" : 74.4}, "connected-to": ["l4" ] },
         {"node-id": "c1", "coord" : {"x" : 19.8, "y" : 65}, "connected-to": ["l2", "l7" ] },
         {"node-id": "c2", "coord" : {"x" : 31.1, "y" : 69}, "connected-to": ["l2", "l3" ] },
         {"node-id": "c3", "coord" : {"x" : 42.5, "y" : 65}, "connected-to": ["l3", "l6" ] },
         {"node-id": "c4", "coord" : {"x" : 31.1, "y" : 58.8}, "connected-to": ["l6", "l7" ] }```
the maximum value in the x coordinate ever needed is `52.2`, and `74.4` in the y axis, so I've set the coordinate checking to those, rounded up, plus a 2 meter buffer (which is a little bigger than the footprint of the model).

That means we accept coordinates for object placement up to `55` and `77`.

**Comment by ivoysey** [comment]
I also updated the wiki with these values.

**Comment by ivoysey** [comment]
that last commit reference is bogus; i meant 59 on LLStaging
